# Generated by Django 5.0.2 on 2024-02-13 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gid", models.CharField(max_length=120, unique=True)),
                ("tracked", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["gid"], name="library_man_gid_46cefb_idx"),
                    models.Index(
                        fields=["tracked"], name="library_man_tracked_5fa14f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("gid", models.CharField(max_length=120, unique=True)),
                (
                    "primary_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContributingArtist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.artist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.song",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["gid"], name="library_man_gid_2ef37b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="contributingartist",
            unique_together={("song", "artist")},
        ),
    ]
