# Generated by Django 5.0.2 on 2024-02-12 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uuid", models.UUIDField()),
                ("tracked", models.BooleanField(default=False)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["uuid"], name="library_man_uuid_91b922_idx"),
                    models.Index(
                        fields=["tracked"], name="library_man_tracked_5fa14f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("uuid", models.UUIDField()),
                (
                    "primary_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.artist",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["uuid"], name="library_man_uuid_0e85ad_idx")
                ],
            },
        ),
    ]
