# Generated by Django 5.0.2 on 2024-02-13 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "download_location",
                    models.CharField(default="../Spotify", max_length=20480),
                ),
                (
                    "temp_path",
                    models.CharField(default="../temp_path", max_length=20480),
                ),
                (
                    "template_folder_album",
                    models.CharField(default="{album_artist}/{album}", max_length=2048),
                ),
                (
                    "template_folder_compilation",
                    models.CharField(default="Compilations/{album}", max_length=2048),
                ),
                (
                    "template_file_single_disc",
                    models.CharField(default="{track:02d} {title}", max_length=2048),
                ),
                (
                    "template_file_multi_disc",
                    models.CharField(
                        default="{disc}-{track:02d} {title}", max_length=2048
                    ),
                ),
                ("download_mode", models.CharField(default="ytdlp", max_length=50)),
                ("log_level", models.CharField(default="INFO", max_length=50)),
                ("premium_quality", models.BooleanField(default=False)),
                ("truncate", models.IntegerField(default=120)),
            ],
        ),
    ]
