# Generated by Django 5.0.2 on 2024-02-13 20:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0002_settings"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Settings",
            new_name="Setting",
        ),
    ]
