# Generated by Django 5.0.2 on 2024-02-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0003_alter_contributingartists_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="uuid",
            field=models.UUIDField(unique=True),
        ),
    ]
