# Generated by Django 5.0.2 on 2024-02-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0004_downloadhistory_delete_setting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadhistory",
            name="completed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
