# Generated by Django 5.0.2 on 2024-02-16 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0005_alter_downloadhistory_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spotify_gid", models.CharField(max_length=2048, unique=True)),
                ("spotify_uri", models.CharField(max_length=2048)),
                ("downloaded", models.BooleanField(default=False)),
                ("total_tracks", models.IntegerField(default=0)),
                (
                    "artist_gid",
                    models.ForeignKey(
                        db_column="artist_gid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library_manager.artist",
                        to_field="gid",
                    ),
                ),
            ],
        ),
    ]
