# Generated by Django 5.0.2 on 2024-02-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0007_rename_artist_gid_album_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="name",
            field=models.CharField(default="missing", max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="album",
            name="wanted",
            field=models.BooleanField(default=True),
        ),
    ]
