# Generated by Django 5.0.2 on 2024-02-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0008_album_name_album_wanted"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedPlaylist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2048)),
                ("url", models.CharField(max_length=2048, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
