# Generated by Django 5.0.2 on 2024-02-23 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0009_trackedplaylist"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="added_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artist",
            name="last_synced_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
