# Generated by Django 5.0.2 on 2024-02-23 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0011_trackedplaylist_auto_track_artists"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trackedplaylist",
            old_name="last_synced",
            new_name="last_synced_at",
        ),
    ]
