# Generated by Django 5.0.2 on 2024-03-01 03:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0012_rename_last_synced_trackedplaylist_last_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="downloaded_at",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
