# Generated by Django 5.0.2 on 2024-03-01 03:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("library_manager", "0013_song_created_at_song_downloaded_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="downloaded_at",
        ),
    ]
