# Generated by Django 5.0.3 on 2025-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0014_remove_song_downloaded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="failed_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="song",
            name="failed_count",
            field=models.IntegerField(default=0),
        ),
    ]
