# Generated by Django 5.0.3 on 2025-01-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_manager", "0015_album_failed_count_song_failed_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="album_type",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
