# Generated by Django 5.1.5 on 2025-02-04 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0016_album_album_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bitrate',
            field=models.IntegerField(default=0),
        ),
    ]
