# Generated by Django 5.1.5 on 2025-02-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0017_song_bitrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_group',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
