# Generated by Django 5.1.5 on 2025-02-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0018_album_album_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='unavailable',
            field=models.BooleanField(default=False),
        ),
    ]
