# Generated by Django 5.1.5 on 2025-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_manager', '0019_song_unavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='file_path',
            field=models.FilePathField(null=True),
        ),
    ]
