default:
  # Default input/output locations
  # Please customize this to your desired location
  # Cookies & PO Tokens are *both* required for HQ downloads
  cookies_location: "/config/cookies.txt"
  po_token: null
  log_level: "INFO"
  no_lrc: false
  overwrite: false
  print_exceptions: true
  disable_missing_tracked_artist_download: false

  # Quick-start development settings - unsuitable for production
  # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
  # SECURITY WARNING: keep the secret key used in production secret!
  SECRET_KEY: 'django-insecure-7e!$54*ii^iyw!963-e3a*r8d0mb)zz@ij6s#s_(0qy(1_^bx*'
  # SECURITY WARNING: don't run with debug turned on in production!
  DEBUG: False
  ALLOWED_HOSTS:
    - '*'
  # Application definition
  INSTALLED_APPS:
    - library_manager.apps.LibraryManagerConfig
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - django_extensions
    - debug_toolbar
    - huey.contrib.djhuey
    - bx_django_utils # https://github.com/boxine/bx_django_utils
    - huey_monitor
  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware
    - debug_toolbar.middleware.DebugToolbarMiddleware
  ROOT_URLCONF: spotify_library_sync.urls
  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: []
      APP_DIRS: True
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages
  WSGI_APPLICATION: spotify_library_sync.wsgi.application
  # Database
  # https://docs.djangoproject.com/en/5.0/ref/settings/#databases
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: "/config/db/db.sqlite3"
      OPTIONS: {
        timeout: 20,  # in seconds
        # see also
        # https://docs.python.org/3.13/library/sqlite3.html#sqlite3.connect
      }
  # Password validation
  # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator
  # Internationalization
  # https://docs.djangoproject.com/en/5.0/topics/i18n/
  LANGUAGE_CODE: en-us
  TIME_ZONE: America/Toronto
  USE_I18N: True
  USE_TZ: True
  # Static files (CSS, JavaScript, Images)
  # https://docs.djangoproject.com/en/5.0/howto/static-files/
  STATIC_URL: /static/
  # Default primary key field type
  # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
  DEFAULT_AUTO_FIELD: django.db.models.BigAutoField
  INTERNAL_IPS:
    - '127.0.0.1'
    - '10.0.2.2'
    - 'localhost'

  HUEY: {
    huey_class: 'huey.SqliteHuey',
    name: 'spotify_library_sync',
    filename: "/config/db/huey.sqlite3",
    immediate: false,
    # immediate_use_memory: true,
  }
