"""
Django settings for spotify_library_sync project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

import django_stubs_ext

django_stubs_ext.monkeypatch()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# HERE STARTS DYNACONF EXTENSION LOAD (Keep at the very bottom of settings.py)
# Read more at https://www.dynaconf.com/django/
import dynaconf  # noqa

settings = dynaconf.DjangoDynaconf(
    __name__,
    PRELOAD_FOR_DYNACONF=[
        "../settings.yaml",
        "*.yaml",
        "/config/settings.yaml",
    ],
    ENVVAR_FOR_DYNACONF="DJANGO_ENV",
    settings_files=[
        "../settings.yaml",
        "*.yaml",
        "/config/settings.yaml",
    ],
)  # noqa

Path("/config/db/").mkdir(parents=True, exist_ok=True)
